-- MySQL Script generated by MySQL Workbench
-- Sun Aug 29 19:32:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book` (
  `id` INT NOT NULL,
  `titel` VARCHAR(60) NOT NULL,
  `author` VARCHAR(60) NOT NULL,
  `co_author` VARCHAR(45) NULL,
  `available_number` INT NULL,
  `delated` TINYINT NOT NULL,
  `created_by` VARCHAR(255) NOT NULL,
  `created_date` DATE NOT NULL,
  `last_modified_by` VARCHAR(255) NULL,
  `last_modifidet_date` DATE NULL,
  `bookcol` VARCHAR(45) NULL,
  `book_id` INT NOT NULL,
  `ordered` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `library`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`user` (
  `id` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `firstn_name` VARCHAR(16) NOT NULL,
  `last_name` VARCHAR(16) NOT NULL,
  `age` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ecess_level` VARCHAR(16) NOT NULL,
  `book_read` INT NULL,
  `debt` TINYINT NULL,
  `books_reading_now` INT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_  user_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_  user_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `library`.`statistic_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`statistic_books` (
  `id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`, `book_id`),
  INDEX `fk_statistic_user_book1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_statistic_user_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
